import { DeleteUser } from './DeleteUser'
import { SpendingLimits } from './SpendingLimits'
import { useEffect, useState } from 'react'
import { Link, Navigate } from 'react-router-dom'
import type { Profile } from '@contracts/contracts'
import type { AdminReport } from '@contracts/admin'
import { api } from '@shared/api/api'
import { AppShell } from '@widgets/AppShell/AppShell'
import './AdminPage.css'

export function AdminPage() {
  const [profile, setProfile] = useState<Profile | null>(null)
  const [error, setError] = useState('')
  const [period, setPeriod] = useState<'all' | 'month'>('all')
  useEffect(() => {
    let active = true
    void api
      .getProfile()
      .then(({ data }) => {
        if (active) setProfile(data)
      })
      .catch((error: unknown) => {
        if (active)
          setError(error instanceof Error ? error.message : 'Could not load your profile.')
      })
    return () => {
      active = false
    }
  }, [])
  if (!profile)
    return (
      <main className="loading-screen">
        {error ? (
          <p role="alert">
            {error} <Link to="/">Back to practice</Link>
          </p>
        ) : (
          <p role="status">Opening admin…</p>
        )}
      </main>
    )
  if (!profile.isAdmin) return <Navigate to="/" replace />
  return (
    <AppShell profile={profile}>
      <section className="admin-page">
        <h1>Admin</h1>
        <p>All users and their recorded AI usage.</p>
        <label className="admin-period">
          Reporting period
          <select
            value={period}
            onChange={(event) => setPeriod(event.target.value as 'all' | 'month')}
          >
            <option value="all">All time</option>
            <option value="month">This month (UTC)</option>
          </select>
        </label>
        <p className="admin-note">
          All time starts when tracking began. Spending includes shared cards generated by each
          user. Missing or unverified usage is excluded from totals and marked below. Spending
          limits use known costs; a final or concurrent request can exceed them.
        </p>
        <AdminUsers key={period} period={period} currentUserId={profile.id} />
      </section>
    </AppShell>
  )
}

function AdminUsers({ period, currentUserId }: { period: 'all' | 'month'; currentUserId: string }) {
  const [cursors, setCursors] = useState<(string | undefined)[]>([undefined])
  const [report, setReport] = useState<AdminReport | null>(null)
  const [error, setError] = useState('')
  const [refresh, setRefresh] = useState(0)
  const [notice, setNotice] = useState('')
  const cursor = cursors.at(-1)
  useEffect(() => {
    let active = true
    void api
      .getAdminUsers(period, cursor)
      .then(({ data }) => {
        if (active) setReport(data)
      })
      .catch((error: unknown) => {
        if (active) setError(error instanceof Error ? error.message : 'Could not load users.')
      })
    return () => {
      active = false
    }
  }, [period, cursor, refresh])
  function reset() {
    setReport(null)
    setError('')
  }
  return (
    <>
      {notice ? <p role="status">{notice}</p> : null}
      <div className="admin-toolbar">
        <p>Page {cursors.length}</p>
        <button
          className="button"
          disabled={!report && !error}
          onClick={() => {
            reset()
            setRefresh((value) => value + 1)
          }}
        >
          Refresh
        </button>
      </div>
      {error ? (
        <p role="alert">{error}</p>
      ) : !report ? (
        <p role="status">Calculating complete usage totals…</p>
      ) : (
        <>
          <div
            className="admin-table-scroll"
            role="region"
            aria-label="User usage totals"
            tabIndex={0}
          >
            <table className="admin-table">
              <caption>Usage through {new Date(report.to).toLocaleString()} · USD</caption>
              <thead>
                <tr>
                  <th scope="col">User</th>
                  <th scope="col">Word tokens</th>
                  <th scope="col">Transcription duration</th>
                  <th scope="col">Total AI spend (USD)</th>
                </tr>
              </thead>
              <tbody>
                {report.users.map((user) => (
                  <tr key={user.id}>
                    <th scope="row">
                      <strong>{user.displayName}</strong>
                      <span>@{user.username}</span>
                      {user.unknownCostCount +
                        user.unknownTokenCount +
                        user.unknownAudioDurationCount +
                        user.unverifiedCount >
                      0 ? (
                        <span className="admin-incomplete">
                          Incomplete usage data: {user.unknownCostCount} missing costs,{' '}
                          {user.unknownTokenCount} missing word token counts,{' '}
                          {user.unknownAudioDurationCount} missing audio durations,{' '}
                          {user.unverifiedCount} unverified receipts.
                        </span>
                      ) : null}
                      <SpendingLimits userId={user.id} username={user.username} />
                      <DeleteUser
                        user={user}
                        self={user.id === currentUserId}
                        onDeleted={() => {
                          setNotice(`Deleted @${user.username}. Recording cleanup is queued.`)
                          setReport((current) =>
                            current
                              ? {
                                  ...current,
                                  users: current.users.filter((row) => row.id !== user.id),
                                }
                              : current,
                          )
                          setRefresh((value) => value + 1)
                        }}
                      />
                    </th>
                    <td>
                      {BigInt(user.knownTokens).toLocaleString()}
                      {user.unknownTokenCount + user.unverifiedCount > 0 ? ' (known)' : ''}
                    </td>
                    <td>
                      {user.knownAudioSeconds.toLocaleString(undefined, {
                        maximumFractionDigits: 2,
                      })}{' '}
                      s{user.unknownAudioDurationCount + user.unverifiedCount > 0 ? ' (known)' : ''}
                    </td>
                    <td title={`$${user.knownCostUsd}`}>
                      {formatCost(user.knownCostUsd)}
                      {user.unknownCostCount + user.unverifiedCount > 0 ? ' (known)' : ''}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {report.users.length === 0 ? <p>No users to show.</p> : null}
          </div>
        </>
      )}
      <nav className="admin-pagination" aria-label="User pages">
        <button
          className="button"
          disabled={cursors.length === 1 || (!report && !error)}
          onClick={() => {
            reset()
            setCursors((value) => value.slice(0, -1))
          }}
        >
          Previous
        </button>
        <button
          className="button"
          disabled={!report?.nextCursor}
          onClick={() => {
            if (report?.nextCursor) {
              reset()
              setCursors((value) => [...value, report.nextCursor!])
            }
          }}
        >
          Next
        </button>
      </nav>
    </>
  )
}

function formatCost(value: string) {
  const [whole, fraction = ''] = value.split('.')
  const trimmed = fraction.replace(/0+$/, '').padEnd(2, '0')
  return `$${BigInt(whole!).toLocaleString()}.${trimmed}`
}
